/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.donutquine;

import java.util.Arrays;

public class Library {
    public static void printAllStrings(String[] strings) {
        System.out.println(Arrays.toString(strings));
    }
}
